### ISSUE TITLE
Contradicting error messages in test files

### ISSUE THREAD

**Issue by steveafrost** [learn-co-students/rails-amusement-park-v-000#142]
Hey, I'm not sure if this is intentional or not. If it is, then it's confusing for the tests to require two different, but very similar, error messages.

**See [spec/features/user_features_spec.rb](https://github.com/learn-co-students/rails-amusement-park-v-000/blob/master/spec/features/user_features_spec.rb)**
- expect(page).to have_content("You do not have enough tickets to ride the #{@ferriswheel.name}")
- expect(page).to have_content("You are not tall enough to ride the #{@rollercoaster.name}")
- expect(page).to have_content("You do not have enough tickets to ride the #{@rollercoaster.name}")

**Whereas the [#take_ride method tests](https://github.com/learn-co-students/rails-amusement-park-v-000/blob/master/spec/models/ride_spec.rb) ask for almost identical, but slightly different errors**
- expect(ride.take_ride).to eq("Sorry. You are not tall enough to ride the #{attraction.name}.")
- expect(ride.take_ride).to eq("Sorry. You do not have enough tickets the #{attraction.name}. You are not tall enough to ride the #{attraction.name}.")

If these are indeed supposed to be two separate error messages, i.e. the user_features are looking for the error to be on the attraction#show view while the #take_ride is looking for the errors described there to be on the page after attraction#show, then I think it needs some clarification. It almost seems like an error as it stands now - to me, at least.

Thanks!

**Comment by gj** [comment]
Hi @steveafrost !

The `#take_ride` tests are checking the return value of the `#take_ride` method, and the `user_features_spec` tests are checking whether those messages get properly added to the appropriate page. The tests have been updated a couple times since this issue was raised, remedying the incorrect `You do not have enough tickets [to ride] the #{attraction.name}` expectation.

Thanks for contributing! 🙂
